import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    padding: 16,
  },
  title: {
    fontSize: 24,
    fontFamily: 'TT Tricks Trial Black',
    color: '#1a1a1a',
    marginBottom: 24,
    textAlign: 'center',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  section: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: '#1a1a1a',
    paddingBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'TT Tricks Trial Bold',
    color: '#1a1a1a',
    marginBottom: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  description: {
    fontSize: 14,
    fontFamily: 'TT Tricks Trial Regular',
    color: '#1a1a1a',
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  currentPath: {
    fontSize: 14,
    fontFamily: 'TT Tricks Trial Medium',
    color: '#1a1a1a',
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  folderPicker: {
    marginTop: 12,
  },
  tagList: {
    maxHeight: 300,
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  buttonsWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 32,
  },
  warningText: {
    fontSize: 12,
    fontFamily: 'TT Tricks Trial Regular',
    color: '#ff0000',
    marginTop: 8,
    fontStyle: 'italic',
  },
  errorText: {
    fontSize: 14,
    fontFamily: 'TT Tricks Trial Regular',
    color: '#ff0000',
    marginBottom: 12,
    textAlign: 'center',
  },
  infoText: {
    fontSize: 14,
    fontFamily: 'TT Tricks Trial Regular',
    color: '#666666',
    marginBottom: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  statsContainer: {
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  statsText: {
    fontSize: 14,
    fontFamily: 'TT Tricks Trial Medium',
    color: '#1a1a1a',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  foldersList: {
    marginTop: 8,
    paddingLeft: 12,
  },
  folderText: {
    fontSize: 12,
    fontFamily: 'TT Tricks Trial Regular',
    color: '#666666',
    marginBottom: 4,
    letterSpacing: 0.5,
  },
});